# Generated by Django 4.2.25 on 2025-11-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanoodleApp', '0002_piece_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyramidBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('levels', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterField(
            model_name='partialsolution',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanoodleApp.kanoodleboard'),
        ),
        migrations.AddField(
            model_name='partialsolution',
            name='pyramid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanoodleApp.pyramidboard'),
        ),
    ]
