# Generated by Django 4.2.25 on 2025-11-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanoodleApp', '0003_pyramidboard_alter_partialsolution_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyramidboard',
            name='name',
            field=models.CharField(default='5-Level Pyramid', max_length=100),
        ),
        migrations.CreateModel(
            name='PyramidSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partial_board', models.JSONField(default=dict, help_text='Initial board state')),
                ('solutions_data', models.JSONField(default=list, help_text='All found solutions')),
                ('solution_count', models.IntegerField(default=0)),
                ('exhausted', models.BooleanField(default=False)),
                ('timed_out', models.BooleanField(default=False)),
                ('pyramid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanoodleApp.pyramidboard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
